# Generated by Django 3.0.1 on 2020-04-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=200)),
                ('active', models.CharField(max_length=100, null=True)),
                ('recovered', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
