# Generated by Django 3.0.5 on 2020-04-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dash',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
