# Generated by Django 3.0.5 on 2020-04-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20200411_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dash',
            name='active',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dash',
            name='deaths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dash',
            name='recovered',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dash',
            name='serious',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dash',
            name='tot_test',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dash',
            name='total',
            field=models.IntegerField(),
        ),
    ]
